version: 2.1

orbs:
  docker: circleci/docker@0.5.20

jobs:
  build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: kemokemo/try-dockle:${CIRCLE_SHA1}
      - run:
          name: Install dockle
          command: |
             apk add --update curl
             VERSION=$(
               curl -I "https://github.com/goodwithtech/dockle/releases/latest" | \
               grep 'Location' | \
               sed -E 's/.*v([0-9\.]+)*$/\1/'
             )
             wget https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.tar.gz
             tar zxvf dockle_${VERSION}_Linux-64bit.tar.gz
             mv dockle /usr/local/bin
      - run:
          name: Scan the local image with Dockle
          command: dockle --exit-code 1 try-dockle:${CIRCLE_SHA1}
workflows:
  version: 2
  release:
    jobs:
      - build
